# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db0ab953dba379525cb878a15a5e6668f373b1fc210787283533d44347146950ddd34c40044cd17168493980a79ac51ac8305fcf3bc618bcb2d4d64e169c8c9f
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  payjp_access_key: <%= ENV["PAYJP_ACCESS_KEY"] %>
  payjp_public_key: <%= ENV["PAYJP_PUBLIC_KEY"] %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID']%>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET']%>

test:
  secret_key_base: db0ab953dba379525cb878a15a5e6668f373b1fc210787283533d44347146950ddd34c40044cd17168493980a79ac51ac8305fcf3bc618bcb2d4d64e169c8c9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  # aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  payjp_access_key: <%= ENV["PAYJP_ACCESS_KEY"] %>
  payjp_public_key: <%= ENV["PAYJP_PUBLIC_KEY"] %>